import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'

const roboto = Roboto({
  weight: ['100', '400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

const pokemon = localFont({
  src: './fonts/pokemon_solid.ttf',
  display: 'swap',
  variable: '--font-pokemon',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${roboto.variable} ${pokemon.variable}`}>
      <body style={{ margin: 0 }}>{children}</body>
    </html>
  )
}
